services:
  # Serviço do Backend (Flask API)
  backend:
    build: .
    container_name: cbf_backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=cbf
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      db:
        condition: service_healthy # <-- ALTERAÇÃO IMPORTANTE AQUI
    networks:
      - cbf-network

  # Serviço do Frontend (Vue.js + Nginx)
  frontend:
    build:
      context: ./frontend/cbf-front
      dockerfile: Dockerfile
    container_name: cbf_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - cbf-network

  # Serviço do Banco de Dados (MySQL)
  db:
    image: mysql:8.0
    container_name: cbf_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cbf
    volumes:
      - db_data:/var/lib/mysql
      - ./database/database_logic.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cbf-network
    # --- ADIÇÃO IMPORTANTE ABAIXO ---
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

# Volumes para persistência de dados
volumes:
  db_data:

# Rede para comunicação entre os contentores
networks:
  cbf-network:
    driver: bridge